### ISSUE TITLE
LoFi's

### ISSUE THREAD

**Issue by marizaswart** [CraftAcademy/slow_food_sinatra_mvc_st_erik#14]
Create lofi's

**Comment by lcegit** [comment]
![customer-1.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a12df617c7a3d0011673eff/125516c66e82c728ace21e0d46eb8189378d8eac9da4ee01e81fe086264c22703d46f9692584b27aba402e520a5d4eaa49095f44f5acda22aee43577984019af80330b2b9b645bf9fa9015ad00b22a8a4a84b7be8c48c1ea3522ee8f9d02.png)

trying this out

**Comment by marizaswart** [comment]
https://docs.google.com/presentation/d/13nmoUxL6XB4dHZGHwvm-jng71PYCGoaZvCAORCeJAys/edit#slide=id.g32d30c98ce_0_55

**Comment by lcegit** [comment]
![Screen Shot 2017-11-21 at 15.37.35.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a12df617c7a3d0011673eff/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76226456f26b7191a379ea0c2856415c4bbe5d4a1f06a3a3dc78e2a436628f0d0aef843f5a77933f11aab0d31fbf08ef738247d7bfbb9850d2aa6c7bb3d4d216744b470a83ed5c3daa984ec959f44ce44d53a01a3564f43b.png)

**Comment by diraulo** [comment]
Nice work on the LoFis :+1:

**Comment by lcegit** [comment]
@diraulo We're going to focus on the customer for the user experience, the restaurant owner might have to deal with the database directly, as suggested by Francesco.
