### ISSUE TITLE
Sketch out database ERD

### ISSUE THREAD

**Issue by marizaswart** [CraftAcademy/slow_food_sinatra_mvc_st_erik#15]
There are three basic elements in ER-Diagrams:

Entities are the "things" for which we want to store information. An entity is a person, place, thing or event.
Attributes are the data we want to collect for an entity.
Relationships describe the relations between the entities.

**Comment by diraulo** [comment]
You should probably upload the ERD here for further comments on it (if any)
Also, it helps to have things in one place, you can always refer to this ticket in future to discuss ERD related issues

**Comment by NegativeKarma** [comment]
![Slow_food_ERD.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a12e9e18f32c20011ab641e/125516c66e82c728ace21e0d46db989534bd85a680ed80669679b2d86b56357c2301a03f32dfa17dbe1329040d5a4df94358594cadf98922f3e53578d8550cffcd7f1d2598694ef1e1c84afd13b0328a498fb7b98b4dc3ed3527e388884a3f0c48.png)
