### ISSUE TITLE
Create core feature: Menu

### ISSUE THREAD

**Issue by lcegit** [CraftAcademy/slow_food_sinatra_mvc_st_erik#35]

**Comment by tochman** [comment]
This issue has no user story. Yet there are two PR's for it. ;-)

**Comment by tochman** [comment]
Also, if it describe something that is visible to a user, it's definitely a `feature` not a `chore`

**Comment by marizaswart** [comment]
Chore change to feature, PR's retracted and new version is being finalised and will use card.
